# Generated by Django 4.0.4 on 2023-03-06 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagevideo',
            name='video_path',
            field=models.FileField(upload_to='static/patient/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
