# Generated by Django 4.0.4 on 2023-03-11 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_mainpagevideo_video_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagevideo',
            name='video_path',
            field=models.FileField(upload_to='patient/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
